### ISSUE TITLE
ai_strategy似乎没生效

### ISSUE THREAD

**Issue by WuTianyi321** [EndsM/MuvLuvCN#7]
经测试，由于不明原因，ai_strategy似乎没有生效，各ai会不断往盟友前线调兵，回退版本到0.2.27也无效。

**Comment by EndsM** [comment]
修好了，你拉下来测试一下

**Comment by WuTianyi321** [comment]
> 修好了，你拉下来测试一下

我这边还是不行，
![image](https://github.com/EndsM/MuvLuvCN/assets/48122470/44ee26d5-869b-4126-a17d-4630c7e09512)
开ob模式看非联还是会开局把很多兵调到盟友前线

**Comment by WuTianyi321** [comment]
#8
